### ISSUE TITLE
Support executing a MSYS shell

### ISSUE THREAD

**Issue by 1138-4EB** [numworks/setup-msys2#1]
The shell in `msys2do.cmd` is set to MINGW64: https://github.com/numworks/setup-msys2/blob/11c006e0b43e6787aa0a09da933391646ee4b8ad/msys2do.cmd#L3

Please, allow to provide this as an envvar or cli arg, so it is possible to start MSYS shells too (required to build PKGBUILD files, i.e., MSYS2 packages).

**Comment by Ecco** [comment]
Yeah, that's a great idea. We personally won't have any use for this so I don't think I'll have the time to write the corresponding code, but I'd happily merge a PR for this 😄

**Comment by 1138-4EB** [comment]
What approach do you suggest?

- Remove line 3 from msys2do.cmd and tell users to `set MSYSTEM=whatever`.
- Or, triplicate msys2do.cmd.
- Or, take the first cli arg passed to msys2do.cmd and use it to set the envvar.

**Comment by Ecco** [comment]
That's a good question. I think I'd go for an option in the yml file:
```yaml
- uses: numworks/setup-msys2@v1
  with:
    msystem: whatever
```

This option would simply be forwarded to the `MSYSTEM` environment variable (or default to `MINGW64`). Then msys2do would just not modify the `MSYSTEM` variable, so this could still be overriden in a per-command action.

**Comment by 1138-4EB** [comment]
I'm trying to test my changes before opening a PR, but I cannot use the action, not even `numworks/setup-msys2@v1`. See https://github.com/1138-4EB/setup-msys2/runs/249792370#step:2:3

@Ecco, does it work for you?

**Comment by Ecco** [comment]
Dude… you're trying to run msys2 on Ubuntu 😁

That being said, it's definitely something we could check.

**Comment by 1138-4EB** [comment]
Stupid of me! Thanks a lot! I even forked this other project of yours to be sure https://github.com/1138-4EB/epsilon/runs/249816649 I seems it is getting late and my brain is starting to complain 😄  My apologies for the noise...

**Comment by Ecco** [comment]
That's allright 😄 Someone else might be bitten by this so I created #2  😄
