### ISSUE TITLE
Availability of MSYS in windows-latest

### ISSUE THREAD

**Issue by eine** [numworks/setup-msys2#25]
This issue is to track the availability of MSYS2 in `windows-latest`. It seems that it is planned to install it instead of the current `mingw` package: actions/virtual-environments#30

When done, we should evaluate the usefulness of this action.

**Comment by Ecco** [comment]
Well, obviously if MSYS2 makes it into the default `windows-latest` then this action will be pointless 😄 I don't think we need a specific issue for this though. Closing 😄

**Comment by eine** [comment]
I think that setting MSYSTEM, path-type or updating can be useful even if MSYS2 is already installed. Precisely, that is what other actions do, such as, setup-python or setup-go.
