### ISSUE TITLE
MSYS repository is not available anymore

### ISSUE THREAD

**Issue by dunnock** [numworks/setup-msys2#29]
```
curl http://repo.msys2.org/distrib/x86_64/msys2-base-x86_64-20190524.tar.xz
curl: (7) Failed to connect to repo.msys2.org port 80: Connection refused
```

This results in failing build for actix-net https://github.com/actix/actix-net/pull/113/checks?check_run_id=488119818

**Comment by Ecco** [comment]
Indeed. The links on [Msys2's homepage](https://www.msys2.org/) are broken too. Hopefully they'll fix it soon enough!

**Comment by dscho** [comment]
The MSYS2 maintainer is aware of it. Apparently it's not too easy to fix... but yes, should be fixed soon.

**Comment by eine** [comment]
@dscho, mind pointing to any relevant issue?

**Comment by selsta** [comment]
@eine https://gitter.im/msys2/msys2

**Comment by klei1984** [comment]
Would it be possible to add an alternative download location to a comparable tar.xz package found at https://github.com/msys2/msys2-installer/releases? In that gitter.im chat link from above someone refers to this page as a potential alternative location.
If tc.downloadTool() fails gracefully without stopping the action a second attempt could be made to a github hosted file as fallback.

**Comment by Ecco** [comment]
It looks like this has been fixed upstream. Closing.
