### ISSUE TITLE
Please remove the action from the github market place

### ISSUE THREAD

**Issue by lazka** [numworks/setup-msys2#37]
For instructions see: https://docs.github.com/en/actions/creating-actions/publishing-actions-in-github-marketplace#removing-an-action-from-github-marketplace

In favor of https://github.com/msys2/setup-msys2

**Comment by dscho** [comment]
Yes, please.

**Comment by Ecco** [comment]
![image](https://user-images.githubusercontent.com/55989/87789700-7453cb00-c80d-11ea-83f7-fece2884c99c.png)

**Comment by lazka** [comment]
@Ecco thank you!

**Comment by Ecco** [comment]
You're welcome :)
